/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The flight in stp app services
 */
export class ACRISFlight {
  /**
   * The airline operating the flight. Either IATA or ICAO must be present
   */
  operatingAirline?: {
    /**
     * The airline's IATA-Code
     */
    iataCode?: string;
    /**
     * The airline's ICAO-Code
     */
    icaoCode?: string;
    /**
     * The long name of airline
     */
    name?: string;
    [k: string]: unknown;
  };
  /**
   * The aircraft-type information
   */
  aircraftType?: {
    /**
     * The aircraft's ICAO-Code
     */
    icaoCode?: string;
    /**
     * The model name of the aircraft
     */
    modelName?: string;
    /**
     * The registration of the aircraft
     */
    registration?: string;
    [k: string]: unknown;
  };
  flightNumber?: FlightNumber;
  /**
   * The code-shares associated with the flight
   */
  codeShares?: FlightNumber1[];
  /**
   * The departure airport as IATA format
   */
  departureAirport?: string;
  /**
   * The arrival airport as IATA format
   */
  arrivalAirport?: string;
  /**
   * Date expressed in UTC. Time element is not used. This date MUST not change once initialized. For a flight SFO-DEN-LHR both flight legs SFO-DEN and DEN-LHR will have the origin date of the SFO departing date (example 2015-10-15).
   */
  originDate?: string;
  departure?: FlightDepartureInformation;
  arrival?: FlightArrivalInformation;
//Excel mapping Air Traffic Control Facility
  airTrafficControlFacility: string;
//Aircraft Approach Category Code

 aircraftApproachCategoryCode: string;
 //Aircraft Dangerous Goods Limitation Code
 aircraftDangerousGoodsLimitationCode : string;



  /**
   * The status of the flight
   */
  flightStatus?:
    | "Canceled"
    | "Diverted"
    | "Scheduled"
    | "Boarding"
    | "GateClosed"
    | "Departed"
    | "InApproach"
    | "Landed"
    | "BagClaimStarted"
    | "FlightFinished";
  /**
   * A list of airports and the corresponding arrival and departure information for stops during the flight. The order in the array represents the flight order.
   */
  via?: {
    /**
     * The via airport as IATA format
     */
    viaAirport?: string;
    departure?: FlightDepartureInformation1;
    arrival?: FlightArrivalInformation1;
    [k: string]: unknown;
  }[];
  /**
   * elements not in the ACRIS standard
   */
  extensions?: {
    counts?: PaxCountExtension;
    nb ?: MeteorologicalEnvironment[];
    OperationalTimes?: OperationalTimes;
    TypeBRawMessage?: string;
    AircraftMovement?: AircraftMovement;
    AircraftTransport?: AircraftTransport;
    AirportFacility?: AirportFacility;
    Route?: AircraftMovementRoute;
    RouteConstraint?: RouteConstraint
    ScheduledAircraftMovement?: ScheduledAircraftMovement;
    aircraftMovementConstraint?: AircraftMovementConstraint;
    aircraftMovementEmergency?:AircraftMovementEmergency;
    aircraftMovementIdentification?:AircraftMovementIdentification;
    aircraftMovementRouteConstraintType?: string;
    aircraftMovementRules?: string;
    aircraftMovementRulesCategoryCode?: string;
    aircraftMovementRulesCode?: string;
    aircraftMovementStatus?: string;
    aircraftMovementTypeCode?: string;
    boundaryCrossingConditionCode?: string;
    CargoItem?: CargoItem;
    

    [k: string]: unknown;
  };
  
  [k: string]: unknown;
}


/**
 * The flight's operating flightNumber
 */
export class FlightNumber {
  /**
   * The airlineCode-part of the flight-number (e.g. EI)
   */
  airlineCode?: string;
  /**
   * The tracknumber-part of the flight-number (e.g. 123)
   */
  trackNumber?: string;
  /**
   * The optional last character of the flight-number.
   */
  suffix?: string;
  [k: string]: unknown;
}
/**
 * The status representation of a flight
 */
export class FlightNumber1 {
  /**
   * The airlineCode-part of the flight-number (e.g. EI)
   */
  airlineCode?: string;
  /**
   * The tracknumber-part of the flight-number (e.g. 123)
   */
  trackNumber?: string;
  /**
   * The optional last character of the flight-number.
   */
  suffix?: string;
  [k: string]: unknown;
}
/**
 * The departure infomation for the flight
 */
export class FlightDepartureInformation {
  /**
   * Scheduled time of departure including time zone. Format ISO-8601 is used.
   */
  scheduled?: string;
  /**
   * Estimated time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  estimated?: string;
  /**
   * Actual time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  actual?: string;
  /**
   * The terminal for the flight
   */
  terminal?: string;
  /**
   * The gate for the flight
   */
  gate?: string;
  /**
   * The check-in information for the passenger
   */
  checkinInfo?: {
    /**
     * The area of check-in facilities for the flight
     */
    checkinLocation?: string;
    /**
     * The time when check-in procedure starts for the flight
     */
    checkInBeginTime?: string;
    /**
     * The time when check-in procedure ends for the flight
     */
    checkInEndTime?: string;
    /**
     * Additional information about the check-in process
     */
    additionalInfo?: string;
    [k: string]: unknown;
  };
  /**
   * A list of airports and the corresponding arrival and departure information for stops during the flight. The order in the array represents the flight order.
   */
  boardingTime?: {
    /**
     * A name (intl) of the booking class - if there are different boarding times for different classes
     */
    bookingClass?: string;
    /**
     * Boarding time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
     */
    time?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * The arrival information for the flight
 */
export class FlightArrivalInformation {
  /**
   * Scheduled time of arrival including time zone. Format ISO-8601 is used.
   */
  scheduled?: string;
  /**
   * Estimated time of arrival including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  estimated?: string;
  /**
   * Actual time of arrival including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  actual?: string;
  /**
   * The terminal for the flight
   */
  terminal?: string;
  /**
   * The arrival gate for the flight. Depending on the buildings of every airport this could be an gate or area the passenger enters the terminal the first time.
   */
  gate?: string;
  /**
   * Provide information for your passengers where the nearest transfer desks for this flight can be found.
   */
  transferInformation?: string;
  baggageClaim?: {
    /**
     * The carousel for baggage claim
     */
    carousel?: string;
    /**
     * expected time when the baggage claim begins
     */
    expectedTimeOnCarousel?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * The departure infomation for the flight
 */
export class FlightDepartureInformation1 {
  /**
   * Scheduled time of departure including time zone. Format ISO-8601 is used.
   */
  scheduled?: string;
  /**
   * Estimated time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  estimated?: string;
  /**
   * Actual time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  actual?: string;
  /**
   * The terminal for the flight
   */
  terminal?: string;
  /**
   * The gate for the flight
   */
  gate?: string;
  /**
   * The check-in information for the passenger
   */
  checkinInfo?: {
    /**
     * The area of check-in facilities for the flight
     */
    checkinLocation?: string;
    /**
     * The time when check-in procedure starts for the flight
     */
    checkInBeginTime?: string;
    /**
     * The time when check-in procedure ends for the flight
     */
    checkInEndTime?: string;
    /**
     * Additional information about the check-in process
     */
    additionalInfo?: string;
    [k: string]: unknown;
  };
  /**
   * A list of airports and the corresponding arrival and departure information for stops during the flight. The order in the array represents the flight order.
   */
  boardingTime?: {
    /**
     * A name (intl) of the booking class - if there are different boarding times for different classes
     */
    bookingClass?: string;
    /**
     * Boarding time of departure including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
     */
    time?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * The arrival information for the flight
 */
export class FlightArrivalInformation1 {
  /**
   * Scheduled time of arrival including time zone. Format ISO-8601 is used.
   */
  scheduled?: string;
  /**
   * Estimated time of arrival including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  estimated?: string;
  /**
   * Actual time of arrival including time zone. Format ISO-8601 is used. Every airport should provide the best information he has, corresponding to the FIDS.
   */
  actual?: string;
  /**
   * The terminal for the flight
   */
  terminal?: string;
  /**
   * The arrival gate for the flight. Depending on the buildings of every airport this could be an gate or area the passenger enters the terminal the first time.
   */
  gate?: string;
  /**
   * Provide information for your passengers where the nearest transfer desks for this flight can be found.
   */
  transferInformation?: string;
  baggageClaim?: {
    /**
     * The carousel for baggage claim
     */
    carousel?: string;
    /**
     * expected time when the baggage claim begins
     */
    expectedTimeOnCarousel?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * passenger and bag counts associated with the flight
 */
export class PaxCountExtension {
  /**
   * list of passenger count statistics
   */
  paxCounts?: PaxCount[];
  [k: string]: unknown;
}
/**
 * Individual Passenger count statistic
 */
export class PaxCount {
  /**
   * the element type being counted (pax or bag - if missing assume pax)
   */
  elementType?: "pax" | "bag";
  /**
   * The count category: (if missing or blank assume total count)
   */
  category?: "total" | "transfer" | "assistance";
  /**
   * optional qualifier for assistance (Wheelchair, Unnaccompanied minor, etc)
   */
  assistanceQualifier?: string;
  transferQualifier?: FlightNumber1;
  /**
   * the passenger count
   */
  count?: number;
  [k: string]: unknown;
}
/**
 * Information about the operational times for the aircraft movement/flight
 */
export class OperationalTimes {
  /**
   * The time when ground handling on an aircraft starts, can be equal to Actual In-Block Time (to be determined locally). This data element is also known in the aviation industry by the acronym ACGT.
   */
  ActualCommenceofGroundHandlingTimeACGT?: string;
  /**
   * The time when de-icing operations on an aircraft starts. Source: CDM implementation manual.This data element is also known in the aviation industry by the acronym ACZT
   */
  ActualCommencementofDeicingTimeACZT?: string;
  /**
   * The actual time taken to de-ice the aircraft (AEZT-ACZT)
   */
  ActualDeIcingDurationADIT?: string;
  /**
   * Actual End of Boarding Time. This data element is also known in the aviation industry by the acronym AEBT
   */
  ActualEndBoardingTimeAEBT?: string;
  /**
   * The time when de-icing operations on an aircraft end. Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym AEZT
   */
  ActualEndofDeicingTimeAEZT?: string;
  /**
   * The time when ground handling on an aircraft ends, can be equal to Actual Ready for Departure Time (to be determined locally). This data element is also known in the aviation industry by the acronym AEGT.
   */
  ActualEndofGroundHandlingTimeAEGT?: string;
  /**
   * Actual Final Approach Time. This data element is also known in the aviation industry by the acronym AFAT.
   */
  ActualFinalApproachTimeAFAT?: string;
  /**
   * The total duration of the ground handling of the aircraft (AEGT-ACGT)
   */
  ActualGroundHandlingDurationAGHT?: string;
  /**
   * The time that an aircraft arrives in blocks (equivalent to airline/handler ATA - Actual Time of Arrival, ACARS = IN). Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym AIBT
   */
  ActualInBlockTimeAIBT?: string;
  /**
   * The time that an aircraft lands on a runway (equivalent to ATC ATA - Actual Time of Arrival = landing, ACARS=ON). Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym ALDT
   */
  ActualLandingTimeALDT?: string;
  /**
   * Actual Last Call Time.
   */
  ActualLastCallTime?: string;
  /**
   * Time the aircraft pushes back/vacates the parking position (equivalent to airline/handlers ATD - Actual Time of Departure &amp; ACARS = OUT). Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym AOBT
   */
  ActualOffBlockTimeAOBT?: string;
  /**
   * De-Icing Ready Time. The time when the aircraft is ready to be deiced. Source: CDM implementation manual.This data element is also known in the aviation industry by the acronym ARZT.
   */
  ActualReadyforDeicingTimeARZT?: string;
  /**
   * When the aircraft is ready for pushback immediately after clearance delivery (all doors are closed and the pushback tractor - ordered by handling agent - is in position. Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym ARDT
   */
  ActualReadyforDepartureTimeARDT?: string;
  /**
   * Actual Start Boarding Time. This data element is also known in the aviation industry by the acronym ASBT
   */
  ActualStartBoardingTimeASBT?: string;
  /**
   * Time that an aircraft receives its start up approval. Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym ASAT
   */
  ActualStartUpApprovalTimeASAT?: string;
  /**
   * Actual Start-up Request Time.This data element is also known in the aviation industry by the acronym ASRT
   */
  ActualStartUpRequestTimeASRT?: string;
  /**
   * The time that an aircraft takes off from the runway. (equivalent to ATC ATD - Actual Time of Departure, ACARS = OFF). Source: CDM implementation manual. This data element is also known in the aviation industry by the acronym ATOT
   */
  ActualTakeOffTimeATOT?: string;
  /**
   * Actual time taken between Actual Landing Time and Actual In Block Time. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym AXIT
   */
  ActualTaxiInDurationAXIT?: string;
  /**
   * Duration between Actual off block time and Actual take-off time. Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym AXOT
   */
  ActualTaxiOutDurationAXOT?: string;
  /**
   * Information about the actual time of operation from the last port of call.  For arrivals this is the actual time of departure from the previous port. For departures this is the  actual time of departure.
   */
  ActualTimeOfOperationLastPortOfCallLPocATO?: string;
  /**
   * The time taken between Actual In-Block Time and Actual Off-Block Time.
   */
  ActualTurnaroundTimeATTT?: string;
  AircraftMovementMeasure?: AircraftMovementMeasure;
  /**
   * A time calculated and issued by the appropriate central management unit, as a result of tactical slot allocation, at which a flight is expected to become airborne. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym CTOT
   */
  CalculatedTakeOffTimeCTOT?: string;
  /**
   * Date and time of entry into approach zone for an inbound aircraft (always UTC).
   */
  EntryintoApproachZoneTime?: string;
  /**
   * The time when de-icing operations on an aircraft is expected to start. Source: CDM implementation manual.This data element is also known in the aviation industry by the acronym ECZT
   */
  EstimatedCommencementofDeIcingTimeECZT?: string;
  /**
   * The time between the estimated start of de-icing and the estimated end of de-icing
   */
  EstimatedDeIcingDurationEDIT?: string;
  /**
   * Estimated End Boarding Time. This data element is also known in the aviation industry by the acronym EEBT
   */
  EstimatedEndBoardingTimeEEBT?: string;
  /**
   * The estimated time when de-icing operations on an aircraft end. Source: CDM implementation manual.This data element is also known in the aviation industry by the acronym EEZT
   */
  EstimatedEndofDeicingTimeEEZT?: string;
  /**
   * The estimated time that an aircraft will arrive in blocks (equivalent to Airline/Handler ETA - Estimated Time of Arrival). Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym EIBT
   */
  EstimatedInBlockTimeEIBT?: string;
  /**
   * The estimated time that an aircraft will touchdown on the runway (equivalent to ATC ETA - estimated time of arrival). Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym ELDT
   */
  EstimatedLandingTimeELDT?: string;
  /**
   * Estimated Last Call Time.
   */
  EstimatedLastCallTime?: string;
  /**
   * The estimated time that an aircraft will leave from blocks (equivalent to Airline/Handler ETA - Estimated Time of Departure). Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym EOBT
   */
  EstimatedOffBlockTimeEOBT?: string;
  /**
   * The estimated time when the aircraft is expected to be ready for de-icing operations. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym ERZT
   */
  EstimatedReadyforDeicingTimeERZT?: string;
  /**
   * Estimated Start Boarding Time.
   */
  EstimatedStartBoardingTime?: string;
  /**
   * The estimated take off time taking into account the Estimated Off Block Time plus Estimated Taxi-Out Time. Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym ETOT
   */
  EstimatedTakeOffTimeETOT?: string;
  /**
   * The estimated time between landing and in-block. Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym EXIT
   */
  EstimatedTaxiInDurationEXIT?: string;
  /**
   * The estimated time between off-block and take off. Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym EXOT
   */
  EstimatedTaxiOutDurationEXOT?: string;
  /**
   * The time estimated by the Aircraft Operator/Ground Handling on the day of operation to turn-round a flight taking into account the operational constraints. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym ETTT
   */
  EstimatedTurnAroundDurationETTT?: string;
  /**
   * The minimum turn-round time agreed with an Aircraft Operator or Ground Handler for a specified flight or aircraft type
   */
  MinimumTurnAroundTimeMTTT?: string;
  /**
   * Planned Last Call Time.
   */
  PlannedLastCallTime?: string;
  /**
   * Planned Start Boarding Time.
   */
  PlannedStartBoardingTime?: string;
  /**
   * The time that an aircraft is scheduled to arrive at its parking position. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym SIBT
   */
  ScheduledInBlockTimeSIBT?: string;
  /**
   * The time that an aircraft is scheduled to depart from its parking position. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym SOBT
   */
  ScheduledOffBlockTimeSOBT?: string;
  /**
   * The time scheduled to turn-round a flight. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym STTT
   */
  ScheduledTurnAroundDurationSTTT?: string;
  /**
   * The target landing time for an aircraft movement. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym TLDT
   */
  TargetLandingTimeTLDT?: string;
  /**
   * Time, taking into account Target Start Up Time and the traffic situation, that an aircraft can expect to pushback (when start-up and pushback are issued separately). Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym TOBT
   */
  TargetOffBlockTimeTOBT?: string;
  /**
   * The time provided by Air Traffic Control taking into account target off-block time, Calculated take off time and/or the traffic situation that an aircraft can expect to receive start-up/pushback approval (when start-up and pushback are issued together). Source: CDM Implementation Manual.This data element is also known in the aviation industry by the acronym TSAT
   */
  TargetStartUpApprovalTimeTSAT?: string;
  /**
   * The target take off time taking into account the target start-up approval time/ target off-block approval time plus estimated taxi-out time. Source: CDM Implementation Manual. This data element is also known in the aviation industry by the acronym TTOT
   */
  TargetTakeOffTimeTTOT?: string;
  [k: string]: unknown;
}
/**
 * Information that enable a Party to track the performance of the Aircraft Movement.
 */
export class AircraftMovementMeasure {
  /**
   * Code to identify the Aircraft Movement Measure
   */
  Code?: string;
  /**
   * Description of the Aircraft Movement Measure
   */
  Description?: string;
  /**
   * Identifier for the Aircraft Movement Measure
   */
  Identifier?: string;
  /**
   * Name assigned to the Aircraft Movement Measure
   */
  Name?: string;
  /**
   * Title assigned to the Aircraft Movement Measure
   */
  Title?: string;
  Value?: string;
  [k: string]: unknown;
}
/**
 * Information about the Aircraft Movement/Flight
 */
export class AircraftMovement {

  /**
   * Information about the status of an Aircraft Movement/Flight
   */
  AircraftMovementStatus?: {
    /**
     * Information indicating whether an Aircraft Movement is cancelled
     */
    Cancelled?: string;
    /**
     * Information that indicates that the Aircraft is operationally complete and ready for departure
     */
    Cleared?: string;
    /**
     * Code indicating the status of the flight
     */
    Code?: string;
    /**
     * Information that indicates if this Flight service has requested a de-icing service.
     */
    DeicingStatus?: string;
    /**
     * Flag that indicates that the flight has been deleted
     */
    Deleted?: string;
    /**
     * Information that informs the Airline and Airport operational staff concerning the status of an Aircraft Movement Segment.
     */
    OperationalStatus?: string;
    /**
     * Information about the Aircraft Movement Segment Status list that can be displayed to the public.
     */
    PublicStatus?: string;
    /**
     * Flag that indicates that the flight is regulated
     */
    Regulated?: string;
    [k: string]: unknown;
  };
  /**
   * Information about the identifiers used for the flight
   */
  AircraftMovementIdentification?: {
    /**
     * Information on Aircraft Callsign as used in flight plans and all Air Traffic Control classs. It is a combination of ATC_Flight_Number and ATC_Operator
     */
    AirTrafficControlCallsign?: string;
    AircraftMovementCodeShare?: AircraftMovementCodeShare;
    /**
     * Information about the publicly displayed Aircraft Movement identifier
     */
    DisplayedIdentifier?: string;
    /**
     * Information about the IATA number for the Aircraft Movement
     */
    IATAFlightNumber?: string;
    /**
     * Information about the IATA code assigned to an Operator of an Aircraft Movement
     */
    IATAOperatorIdentifier?: string;
    /**
     * The ICAO identification for an Aircraft Movement. A single alphanumeric string giving an ICAO compliant representation of the main movement identifier. This will include a 3 character ICAO carrier code, flight number stripped of leading zeroes where necessary and an optional suffix character.
     */
    ICAOIdentifier?: string;
    /**
     * Information about the ICAO number for the Aircraft Movement.
     */
    ICAONumber?: string;
    /**
     * Information about the number assigned to an Aircraft Movement
     */
    Number?: string;
    /**
     * Information about the scheduled time of Arrival or Departure Aircraft Movement
     */
    ScheduledDateTime?: string;
    /**
     * Information about the optional characters appended to some flight numbers. Some suffices may have specific meanings e.g. C=charter flight, P=positioning flight, T=training flight, Y=Delayed from yesterday. However, these meanings are not standard across all companies and systems so the IATA Service Type element should be used in preference
     */
    Suffix?: string;
    /**
     * Information about a unique identifier assigned by the Airport Party's Operational Database System (AODB). It is also the numeric identifier assigned to every Aircraft Ground Movement by the AODB which provides a single unique key to identify a particular Ground Movement record.
     */
    SystemIdentifier?: string;
    /**
     * Information that identifies a turnaround Aircraft Movement.
     */
    TurnRoundIdentifier?: string;
    [k: string]: unknown;
  };
  /**
   * Information about whether the flight is an Arrival (A) or Departure (D)
   */
  ArrivalOrDeparture?: string;
  /**
   * Information which if set to 'True', indicates that additional security checks are required for the Arrival part of the Movement Segment.
   */
  ArrivalSecurityCheck?: boolean;
  /**
   * Information about whether the displayed information should be automatic (time based) or manual (using show to public value)
   */
  AutomaticProcessing?: string;
  /**
   * Information about the Baggage Reclaim location to be displayed
   */
  BaggageReclaim?: string;
  /**
   * IATA code of the airline carrier for the flight
   */
  CarrierCode?: string;
  /**
   * Information about the displayed checkin zone. it may be different from the root checkin zone
   */
  CheckinZone?: string;
  /**
   * Comments that may be displayed along side other information (e.g. next update time, delayed)
   */
  Comments?: string;
  /**
   * The location type at which de-icing will occur. It must be one of two values. STAND, where the deicing will be performed on-stand or PAD where the deicing will be performed at a remote pad (e.g. JEDI or VADER)
   */
  DeicingMode?: string;
  /**
   * The pad at which deicing will/has occurred. This should only be populated when DeicingMode is PAD.
   */
  DeicingPadLocation?: string;
  /**
   * The identifier of the Rig equipment. This could be the asset number of the de-icing equipment where the equipment is owned by Airport (from its Asset Ledger). Where Airport does not own the equipment, this field should be omitted.
   */
  DeicingRigEquipment?: string;
  /**
   * The Stand at which deicing will/has occurred. This should only be populated when DeicingMode is STAND.
   */
  DeicingStandLocation?: string;
  /**
   * Information which if set to 'True', indicates that additional security checks are required for the Departure part of the Aircraft Movement.
   */
  DepartureSecurityCheck?: boolean;
  /**
   * Free text information about the Aircraft Movement
   */
  Description?: string;
  /**
   * Information that indicates whether the aircraft movement information should be shown to the public
   */
  Display?: boolean;
  /**
   * Information that indicates after what time the aircraft movement is shown to the public
   */
  DisplayFromTime?: string;
  /**
   * Information that indicates after what time the aircraft movement is no longer shown to the public
   */
  DisplayUntilTime?: string;
  /**
   * Information about the Diversion Airport Facility
   */
  DivertAirport?: string;
  /**
   * Information about the code of the Airport Facility to which an Aircraft Transport has been diverted
   */
  DivertAirportFacilityCode?: string;
  /**
   * Information about the indicator for a diversion
   */
  DivertIndicator?: string;
  /**
   * Information on the reason for the diversion
   */
  DivertReason?: string;
  /**
   * Information that describes the code for the divert reason
   */
  DivertReasonCode?: string;
  /**
   * The Estimated Operating DateTime to be displayed
   */
  EstimatedDateTime?: string;
  /**
   * IATA Service Type Classification
   */
  FlightClassification?: string;
  /**
   * Information about the displayed aircraft movement. It includes operator code, formatted flight number and optional suffix
   */
  FlightNumber?: string;
  /**
   * The origin/destination for the aircraft movement
   */
  FlightOriginOrDestination?: string;
  /**
   * Origin Stand for a Ground Movement i.e. where the Aircraft Transport was moving from.
   */
  FromStand?: string;
  /**
   * Information about the gate that is displayed.
   */
  Gate?: string;
  /**
   * The IATA code for the originating airport facility for the movement (flight).
   * Also referred to as Aerodrome of Departure. [FIXM]
   */
  InboundOrigin?: string;
  /**
   * The Actual Operating DateTime to be displayed
   */
  OperatedDateTime?: string;
  /**
   * The IATA code for the destination airport facility for the movement (flight).
   * Also referred to as Aerodrome of Destination [FIXM]
   */
  OutboundDestination?: string;
  /**
   * Information on the Flight Service Priority on allocated Slot
   */
  Priority?: string;
  /**
   * Information that indicates when the aircraft movement is promoted on the display device
   */
  PriorityDisplay?: boolean;
  /**
   * information about the repeat or departure attempt number for an Aircraft Movement.
   */
  RepeatNumber?: string;
  /**
   * Information about the scheduled time of Arrival or Departure Aircraft Movement
   */
  ScheduledDateTime?: string;
  /**
   * Information that indicates that the Flight Service requires special handling including wheelchairs. This is a repeating group of up to 3 codes (to allow multiple codes to be provided)
   */
  SpecialNeedsIndicator?: string;
  /**
   * Information on whether an Aircraft Movement Stop is a Technical (transit) Stop. If true, this is a Technical Stop. If false, it is not a Technical Stop.
   */
  TechnicalStop?: boolean;
  /**
   * Information about the terminal related to the aircraft movement
   */
  Terminal?: string;

  airfileAircraftMovementCode?: string;


  actualTimeOfArrival?: string; // Actual Time Of Arrival
  actualTimeOfDeparture? : string; // Actual Time Of Departure
  airfileIndicatorCode? :string; // Airfile Indicator Code
  alternateAirport?: string; // Alternate Airport
  arrivalAirport?: string;  //Arrival Airport
  arrivalAirportSlotIdentification: string;//Arrival Airport Slot Identification
  atOrAboveAltitudeCode : string;  //At Or AboveAltitudeCode
  cruiseClimbLevel?: string//Cruise Climb Level
  cruiseClimbSpeed?: string; //Cruise Climb Speed
  cruisingLevelChangeActivation?: string;//Cruising Level Change Activation
  cruisingLevelChangeLevel?: string; // Cruising Level Change Level
  cruisingSpeedChangeActivation?: string; //Cruising Speed Change Activation
  cruisingSpeedChangeSpeed?: string ; //Cruising Speed Change Speed
  currentModeACode?: string ; //Current Mode A Code
  delayDuration?: string; // Delay Duration
  delayReason?: string; //Delay Reason
  delayReference?: string; //Delay Reference
  delayType?: string; //Delay Type
  departureAirportSlotIdentification?: string ; //Departure Airport Slot Identification
  destinationAirport?: string; //Destination Airport
  destinationAirportAlternate?: string ;//Destination Airport Alternate
  destinationAirportPrevious?: string;//Destination Airport Previous
  estimatedAircraftTakeoffMass?: string ;//Estimated Aircraft Takeoff Mass
  estimatedElapsedTime?: string ;// Estimated Elapsed Time
  estimatedOffBlockTime?: string;  //Estimated Off Block Time
  estimatedOffBlockTimePrevious?: string; 
  flightPlanOriginatorParty?: string ; //Flight Plan Originator Party
  flightPlanSubmitterParty?: string; //Flight Plan Submitter Party
  flightRuleType?: AircraftMovementRuleType; //Flight Rule Type
  fuelEnduranceDuration?: string;//Fuel Endurance Duration
  gufiOriginatorParty?: string; //GUFI Originator Party
  inboundOrigin?: string;  // Inbound Origin
  inboundOriginPrevious?: string;  // Inbound Origin Previous
  operator?: string;
  personsOnBoardQuantity?: string;    // Persons On Board Quantity
  pilotInCommand?: string;//Pilot In Command
  profilePointAirSpeed?: string; //Profile Point Air Speed
  profilePointDistance?: string; // Profile Point Distance
  profilePointAltitude?: string;  // Profile Point Altitude
  profilePointSequenceIdentifier?: string // Profile Point Sequence Identifier
  profilePointTimeDuration?: string;  // Profile Point Time Duration
  remarks?: string;
  runwayLandingDirection?: string; // Runway Landing Direction
  runwayTakeoffDirection?: string;  // Runway Takeoff Direction
  specialHandlingReason?: string; // Special Handling Reason
  speedScheduleInitialSpeed?: string;// Speed Schedule Initial Speed
  speedScheduleSubsequentSpeed?: string; // Speed Schedule Subsequent Speed
  takeOffAlternateAerodrome?: string; //Take Off Alternate Aerodrome



  //Alternate Airport
  [k: string]: unknown;
}
/**
 * Information about the Code Shares for the flight
 */
export class AircraftMovementCodeShare {
  /**
   * Information about the displayed aircraft movement code share.
   */
  Number?: string;
  /**
   * Flag to indicate whether the code share information is to be provided to the public
   */
  ShowToPublic?: boolean;
  [k: string]: unknown;
}
/**
 * Information about the Aircraft (Aircraft Transport) used in the Aircraft Movement/Flight
 */
export class AircraftTransport {
  /**
   * Aircraft Description
   */
  AircraftDescription?: string;
  /**
   * Information about the earliest delivery date and time associated with a ground transport
   */
  EarliestDeliveryDateTime?: string;
  /**
   * Future max takeoff weight
   */
  FutureMaximumTakeOffWeight?: string;
  /**
   * Information on whether some guidance is required for the Aircraft Transport
   */
  GuidanceRequired?: boolean;
  /**
   * Information about the latest delivery date and time associated with a ground transport
   */
  LatestDeliveryDateTime?: string;
  /**
   * Information about the mode of transport
   */
  Mode?: string;
  /**
   * Noise certification indicator
   */
  NoiseCertificationIndicator?: string;

  AircraftAddress?: string;
  /**
   * Information or indicator that Aircraft has changed stands
   */
  StandChangeIndicator?: string;
  /**
   * Information on whether a Coach Vehicle is required for the Aircraft Transport
   */
  VehicleRequired?: boolean;
  AircraftTransportType?: AircraftTransportType;

  ColoursAndMarkings?: string;
  AircraftType?: string;
  WakeTurbulenceCategory?: string;

  formation?: AircraftTransportFormation;

  /**
   * Information about equipment on board an aircraft.
   */
  AircraftTransportEquipment?: {
    Description?: string;
    Identifier?: string;
    Mode?: string;
    /**
     * Category of equipment on board an aircraft. Values can include Primary and Secondary Surveillance Radar, etc.
     */
    AircraftTransportEquipmentCategory?: {
      /**
       * Description of the Aircraft Transport Equipment Category
       */
      Description?: string;
      /**
       * Identifier of the Aircraft Transport Equipment Category
       */
      Identifier?: string;
      [k: string]: unknown;
    };
    /**
     * Type of equipment on board an aircraft. Values can include Communications, Navigation, Datalink, Surveillance, Survival.
     */
    AircraftTransportEquipmentType?: {
      /**
       * Description of the Aircraft Transport Equipment Type
       */
      Description?: string;
      /**
       * Identifier of the Aircraft Transport Equipment Type
       */
      Identifier?: string;
      [k: string]: unknown;
    };
  CommunicationCapabilityCode?: string[];
  datalinkCommunicationCapabilityCodeList? : string[];
  dinghies? : DinDinghy ;
  emergencyRadioCapabilityTypeList? : string;
  navigationCapabilityCodeList?: string;
  lifeJacketType?: string;
  navigationAidDesignator ?: string;
  navigationCapabilityCode?: string;
  otherCommunicationCapabilities?: string;
  otherDatalinkCapabilities?: string;
  otherNavigationCapabilities?: string;
  otherSurveillanceCapabilities?: string;
  performanceBasedCode?: string;
  surveillanceCapabilityCode?: string;
  survivalEquipmentRemarks?: string;
  survivalEquipmentType?: string;
  SelectiveCallingCode?: string
    [k: string]: unknown;
  };
  /**
   * Information about a specific cabin within the Aircraft
   */
  AircraftTransportCabinConfiguration?: {
    /**
     * Information about the Aircraft Cabin.
     */
    Cabin?: string;
    /**
     * A business defined code assigned to the category of Cabin
     */
    CabinClassType?: string;
    /**
     * Information about the Aircraft cabin category. Supported by a PADIS enumeration list (PADIS 9873).
     */
    CabinType?: string;
    /**
     * Information about the compartment on an Aircraft
     */
    Compartment?: string;
    /**
     * Information about the seating capacity in each cabin. Use a repeating group with cabin type
     */
    SeatCapacity?: string;
    /**
     * Information about the number of seats on the Aircraft.
     */
    SeatCount?: string;
    /**
     * Information about the status of seats which includes 'New', 'Update' and 'Delete'
     */
    Status?: string;
    [k: string]: unknown;
  };
  /**
   * Information about the load carried by the Aircraft Transport on departure from the Host Airport
   */
  AircraftTransportLoad?: {
    /**
     * Total weight of ballast on aircraft
     */
    BallastWeight?: string;
    /**
     * Dead load - total weight on aircraft
     */
    DeadLoad?: string;
    [k: string]: unknown;
  };
  /**
   * Information about the identifiers used to identify the Aircraft Transport
   */
  AircraftTransportIdentifier?: {
    /**
     * Information about the Aircraft Transport's Body Type
     */
    AircraftBodyType?: string;
    /**
     * Information about the version of the Aircraft Transport
     */
    AircraftVersion?: string;
    /**
     * Information that describes the required code that identifies the Aircraft Transport
     */
    CodeRequired?: string;
    /**
     * Airline ship/fleet number as assigned by the airline
     */
    FleetNumber?: string;
    /**
     * Information about the general Aircraft Type Code
     */
    GeneralTypeCode?: string;
    /**
     * Information on the group code for the Aircraft Transport
     */
    GroupCode?: string;
    /**
     * Information about the IATA subtype classification for the IATA Aircraft Subtype. Use SSIM Appendix A.
     */
    IATASubtypeCode?: string;
    /**
     * Information about the Aircraft Transport type using IATA format. e.g. 743 for a Boeing 747-300.
     */
    IATATypeCode?: string;
    /**
     * Information about the Aircraft type using ICAO format. e.g. B743 for a Boeing 747-300.
     */
    ICAOTypeCode?: string;
    /**
     * Information about the registration of the Aircraft Transport.
     */
    Registration?: string;

    TailNumber?: string;
  };
  [k: string]: unknown;
}
/**
 * Type of aircraft transport
 */
export class AircraftTransportType {
  /**
   * Information about the IATA subtype classification for the IATA Aircraft Subtype. Use SSIM Appendix A.
   */
  IATASubtypeCode?: string;
  /**
   * Transportation type using IATA format. e.g. 743 for a Boeing 747-300. Use SSIM Appendix A.
   */
  IATATypeCode?: string;
  /**
   * Transportation type using ICAO format. e.g. B743 for a Boeing 747-300.
   */
  ICAOTypeCode?: string;
  WakeTurbulenceCategory?: WakeTurbulenceCategory;

  numberOfAirCraft?: number;
  type?: string;
  [k: string]: unknown;
}
/**
 * Wake turbulence category
 * The message shall indicate the wake turbulence category of that aircraft type. The IFPS shall accept only the following 4 wake turbulence categories:
 * L (light), M (medium), H (heavy) or J (super).
 * L Shall be inserted for an aircraft with a maximum certified take off mass of 7000 kg or less.
 * M Shall be inserted for an aircraft with a maximum certified take off mass of less than 136000 kg but more than 7000 kg.
 * H Shall be inserted for an aircraft with a maximum certified take off mass of less than 560000kg but more than 136000 kg.
 * J Shall be inserted for an aircraft with a maximum certified take off mass of 560000kg or more.
 */
export class WakeTurbulenceCategory {
  Code?: string;
  Description?: string;
}
/**
 * Information about the Host Airport
 */
export class AirportFacility {
  /**
   * The code assigned to the facility (airport facility) by IATA to the Host Airport
   */
  IATAIdentifier?: string;

    /**
   * The code assigned to the facility (airport facility) by ICAO to the Host Airport
   */
    ICAOdentifier?: string;
   /**
    * The primary official name of an aerodrome as designated by an appropriate authority. [AIXM 5.1]

    */
   Name?: string;
  /**
   * Information about the runway used by this flight
   */
  RunwayFacility?: {
    /**
     * Runway identifier. For example, 27L, 09R, 23.
     */
  RunwayIdentifier?: string;
    [k: string]: unknown;
  };
  /**
   * Information about the stands used by this flight
   */
  StandFacility?: {
    /**
     * Information about the stand the Aircraft used directly after landing which is not updated by ground movements. Stand/parking area at which an aircraft originally parked on arrival at the Airport and from which passengers would have disembarked.
     */
    ArrivalStand?: string;
    /**
     * Information which indicates if coaching service is required or not. By default, omission of this element will imply that coaching is not required.
     */
    CoachingIsRequired?: boolean;
    /**
     * Stand number provisionally allocated to the Aircraft Movement
     */
    ProvisionalStandNumber?: string;
    /**
     * Information about stand hold conflicting stand. Stand/parking area which is causing a hold condition to exist for a particular aircraft. In the case of a standard hold, the conflicting stand will always be the same as the main allocated stand but for adjacency holds, it may not be immediately obvious which adjacent stand is causing the hold and so it is explicitly named here.
     */
    StandHoldConflictingStand?: string;
    /**
     * Information on whether a stand hold is required. True=aircraft must wait for allocated stand to become vacant, False=aircraft may come on stand immediately. By default, omission of this element will imply that a hold is not required.
     */
    StandHoldRequired?: boolean;
    /**
     * Location of the stand
     */
    StandLocation?: string;
    /**
     * Stand number
     */
    StandNumber?: string;
    /**
     * Type of stand
     */
    StandType?: string;
    [k: string]: unknown;
  };
  /**
   * Details of a specific terminal used by the flight
   */
  TerminalFacility?: {
    /**
     * Code for the Terminal
     */
    Code?: string;
    /**
     * Description of the Terminal
     */
    Description?: string;
    /**
     * Information about the Check-In Zone used by the flight
     */
    CheckinZoneFacility?: {
      /**
       * DateTime at which Checkin ended
       */
      CheckinEndTime?: string;
      /**
       * DateTime at which Checkin started
       */
      CheckinStartTime?: string;
      /**
       * Checkin status description
       */
      CheckinStatus?: string;
      /**
       * Description of the checkin zone
       */
      CheckinZoneDescription?: string;
      /**
       * Identifier for the checkin zone for the aircraft movement
       */
      CheckinZoneIdentifier?: string;
      [k: string]: unknown;
    };
    /**
     * Information about the Baggage reclaim facilities used by the flight
     */
    BagItemDeliveryCarousel?: {
      /**
       * Actual time at which the first bag is received
       */
      ActualFirstBagTime?: string;
      /**
       * Actual time at which the last bag is received
       */
      ActualLastBagTime?: string;
      /**
       * Information on the status of the Baggage reclaim
       */
      BaggageReclaimStatus?: string;
      /**
       * Information about the Carousel Number from which the Bag Item will be delivered
       */
      CarouselNumber?: string;
      /**
       * Information about the Conveyor Number from which the Bag Item will be delivered
       */
      ConveyorNumber?: string;
      /**
       * Information about the Legacy FIDS Check-in Zone from which the Bag Item will be delivered
       */
      LegacyFIDSCheckinZone?: string;
      /**
       * Information about the secondary Carousel Number from which the Bag Item will be delivered
       */
      SecondaryCarouselNumber?: string;
      [k: string]: unknown;
    };
    /**
     * Information about the gates used by the flight
     */
    GateFacility?: {
      /**
       * Information about general remarks
       */
      GeneralRemarks?: string;
      /**
       * Previous Gate number after a late change has been made.
       */
      PreviousGate?: string;
      /**
       * Information about the additional location used to transfer passengers to or from remote parking positions
       */
      RemoteOperationGate?: string;
      /**
       * Secondary Gate Number
       */
      SecondaryGateNumber?: string;
      StaffReadinessStatus?: StaffReadinessStatus;
      GateFacilityOperationalTimes?: GateFacilityOperationalTimes;
      PassengerBoardingStatus?: PassengerBoardingStatus;
      PassengerGateInstruction?: PassengerGateInstruction;
      PierFacility?: PierFacility;
      AirJetty?: AirJetty;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
}
/**
 * Information about the status of staff readiness for operating the gate.
 */
export class StaffReadinessStatus {
  /**
   * If set, information indicates that staff is ready for gate open event
   */
  StaffReadyForGateControl?: boolean;
  [k: string]: unknown;
}
/**
 * Information about the operational times for the Gate Facility
 */
export class GateFacilityOperationalTimes {
  /**
   * Actual time at which the gate closed
   */
  ActualGateCloseTime?: string;
  /**
   * Actual time at which the gate opened
   */
  ActualGateOpenTime?: string;
  /**
   * Information about the gating due date and time
   */
  GatingDueDateTime?: string;
  /**
   * Expected time at which the gate will open
   */
  PlannedGateOpenTime?: string;
  [k: string]: unknown;
}
/**
 * Information about the status of passenger boarding
 */
export class PassengerBoardingStatus {
  /**
   * Information about local boarding status at gate
   */
  StatusAtGate?: string;
  [k: string]: unknown;
}
/**
 * Information about the instructions given to passengers about how to proceed at Airport gates.
 */
export class PassengerGateInstruction {
  /**
   * Information to head towards passport control
   */
  GoToPassportControl?: string;
  [k: string]: unknown;
}
/**
 * A terminal pier infrastructure facility is a raised structure, including bridge and building supports and walkways, typically supported by widely spread piles or pillars.
 */
export class PierFacility {
  /**
   * Description of the pier on which the gate being used to board a flight is located
   */
  Description?: string;
  /**
   * Information about pier on which the gate being used to board a flight is located
   */
  Identifier?: string;
  [k: string]: unknown;
}
/**
 * A structure used at airports that allows aircraft passengers to board and unboard a plane to the airport's gate.
 */
export class AirJetty {
  /**
   * Information about a Jetty's Hire Code
   */
  AirJettyHireCode?: string;
  /**
   * Information about the different types of Air Jetties
   */
  AirJettyType?: string;
  [k: string]: unknown;
}
/**
 * Information about the Route of the Aircraft Movement
 */
export class AircraftMovementRoute {
  /**
   * Description of the route of the aircraft movement.
   */
  Description?: string;
  /**
   * Identifier for the route.
   */
  Identifier?: string;
  /**
   * Requested flightlevel (in flightlevel number, tens of meters or hundreds of feet). For example F360.
   */
  RequestedFlightLevel?: string;
  /**
   * The point at : which a change of Requested Flight Level is required.
   */
  RequestedFlightLevelPoint?: string;
  /**
   * Information that indicates the type of Flight service. Examples include I=international, D=domestic, C=Common Travel Area (Irish Republic and Channel)
   */
  RouteInternationalDomestic?: string;
  RouteSegment?: RouteSegment;
  /**
   * A string of route elements complying with PANS-ATM Item 15c
   */
  RouteText?: string;
  /**
   * Information about a Standard Instrument Departure ending at a designated point. For example E.g. KOGAL1A and KOGAL.
   */
  StandardInstrumentDeparture?: string;
  /**
   * True airspeed (in kilometers per hours or knots).
   */
  TrueAirspeed?: string;
  /**
   * The point at which a change of airspeed is requested.
   */
TrueAirspeedPoint?: string;
airfileRouteStartTime?: string; //Airfile Route Start Time
alongRouteDistance?: string; // Along RouteDistance
altimeterSetting?: string;  //  Altimeter Setting
boundaryCrossingClearedLevel?: string; // Boundary Crossing Cleared Level
boundaryCrossingCondition?: string;
boundaryCrossingLevel?: any;
boundaryCrossingPoint?: any;
boundaryCrossingTime?: string;
cruisingLevel?: any;
cruisingSpeed?: string
divertAirport?: string;
elementStartPoint?: any;
estimatedElapsedTimeLongitude?: string;
estimatedElapsedTimePoint?: string
estimatedElapsedTimeRegion?: string;
flightRulesChange?: string;
levelAltitude?: string;
modifiedRouteItemCode?: string;
modifiedRouteItemReference?: string
otherRouteDesignator?: string;
position?: string;
predictedAirspeed?: string;
predictedGroundspeed?: string;
rankedTrajectory?: string;
reclearanceInFlightRoute?: string;
routeChange?: string;
routeDesignator?: string;
routeToRevisedDestination?: string;
routeTruncationCode?: string;
standardInstrumentArrivalIdentifier?: any;
standardInstrumentDepartureIdentifier?: string;
totalEstimatedElapsedTime?: string;
trajectoryPointDescription?: string;
trajectoryPointProperty?:string;
trajectoryPointPropertyType?:string;
verticalRange?:string;
rankedTrajectoryIdentifier?: string;

[k: string]: unknown;
}
/**
 * Information about the Route of the Aircraft Movement
 */
export class RouteSegment {
  /**
   * Description of the route of the aircraft movement.
   */
  Description?: string;
  /**
   * Identifier for the route segment.
   */
  Identifier?: string;
  /**
   * Requested flightlevel (in flightlevel number, tens of meters or hundreds of feet). For example F360.
   */
  RequestedFlightLevel?: string;
  /**
   * The point at : which a change of Requested Flight Level is required.
   */
  RequestedFlightLevelPoint?: string;
  /**
   * True airspeed (in kilometers per hours or knots).
   */
  TrueAirspeed?: string;
  /**
   * The point at which a change of airspeed is requested.
   */
  TrueAirspeedPoint?: string;
  [k: string]: unknown;
}
/**
 * Information about the scheduled Aircraft Movement/Flight, often known as the Flight Plan for a specific aircraft movement.
 */
export class ScheduledAircraftMovement {
  /**
   * Name and location of alternate Airport if no ICAO location exists (Also referred to as ALTNZ)
   */
  AlternateAirport?: string;
  /**
   * ICAO identifier of the Airport of departure
   */
  DepartureAirportICAOCode?: string;
  /**
   * ICAO identifier of the destination Airport
   */
  DestinationAirportICAOCode?: string;
  /**
   * Total estimated elapsed time in hours and minutes. For a flight plan received from an aircraft in flight, the total estimated elapsed time is the estimated time from the first point of the route to which the flight plan applies to the termination point of the flight plan. [DOC 4444]
   */
  EstimatedDuration?: string;
  EstimatedTimeofArrival?: string;
  /**
   * Other necessary information for the scheduled aircraft movement. [DOC 4444]
   */
  OtherInformation?: string;
  /**
   * Plain language remarks, as ICAO field 18 RMK/.
   */
  Remark?: string;
  /**
   * Information about the identifiers used for the flight
   */
  ScheduledAircraftMovementIdentification?: {
    AircraftMovementRuleType?: AircraftMovementRuleType;
    AircraftMovementType?: AircraftMovementType;
    /**
     * Information on Aircraft Callsign as used in flight plans and all Air Traffic Control classs. It is a combination of ATC_Flight_Number and ATC_Operator
     */
    AirTrafficControlCallsign?: string;
    /**
     * Information about the IATA number for the Aircraft Movement
     */
    IATAFlightNumber?: string;
    /**
     * Information about the IATA code assigned to an Operator of an Aircraft Movement
     */
    IATAOperatorIdentifier?: string;
    /**
     * The ICAO identification for an Aircraft Movement. A single alphanumeric string giving an ICAO compliant representation of the main movement identifier. This will include a 3 character ICAO carrier code, flight number stripped of leading zeroes where necessary and an optional suffix character.
     */
    ICAOIdentifier?: string;
    /**
     * Information about the ICAO number for the Aircraft Movement.
     */
    ICAONumber?: string;
    /**
     * Unique Flight plan identifier assigned by the Initial Flight Plan Processing System (IFPS).
     */
    Identifier?: string;
    /**
     * Information about the number assigned to an Aircraft Movement
     */
    Number?: string;
    /**
     * Information about the scheduled time of Arrival or Departure Aircraft Movement
     */
    ScheduledDateTime?: string;
    /**
     * Information about the optional characters appended to some flight numbers. Some suffices may have specific meanings e.g. C=charter flight, P=positioning flight, T=training flight, Y=Delayed from yesterday. However, these meanings are not standard across all companies and systems so the IATA Service Type element should be used in preference
     */
    Suffix?: string;
    /**
     * Information about a unique identifier assigned by the Airport Party's Operational Database System (AODB). It is also the numeric identifier assigned to every Aircraft Ground Movement by the AODB which provides a single unique key to identify a particular Ground Movement record.
     */
    SystemIdentifier?: string;
    /**
     * Information that identifies a turnaround Aircraft Movement.
     */
    TurnRoundIdentifier?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * The type of flight rule that a pilot intends to fly. ICAO Doc 4444.
 * I if it is intended that the entire flight will be operated under the IFR
 * V if it is intended that the entire flight will be operated under the VFR
 * Y if the flight initially will be operated under the IFR, followed by one or more subsequent changes of flight rules
 * Z if the flight initially will be operated under the VFR, followed by one or more subsequent changes of flight rules
 */
export class AircraftMovementRuleType {
  Code?: "I" | "V" | "Y" | "Z";
  Description?: string;
  [k: string]: unknown;
}
/**
 * The type of flight when so required by the appropriate ATS authority. ICAO Doc 4444.
 * S if scheduled air service
 * N if non-scheduled air transport operation
 * G if general aviation
 * M if military
 * X if other than any of the defined categories above.
 */
export class AircraftMovementType {
  Code?: "S" | "N" | "G" | "M" | "X";
  Description?: string;
  [k: string]: unknown;
}


export class DinDinghy {
  totalCapacity?: number;
  color?:string;
  quantity?: number;
  cover?: string;
  persoCapacity: number;
  


}
export class AircraftMovementConstraint {
  applicabilityDescription?: string;
  restrictionReference? : string;
  impactDescription?: string;


}

export class AircraftMovementEmergency {
actionTaken?: string
atsOriginatorIcaoIdentifier?:string;
emergencyDescription?: string;
determinationMethod?: string;
lastContactATSUnit? : string;
lastContactFrequency?: string;
lastContactTime?: string;
lastKnownPositionLocation?: string;
lastKnownPositionTime?: string;
otherInformation?: string;
phaseIdentifier?: string;
radioFailureRemarks?: string;
remainingCommunicationCapability?: string;
}

export class AircraftMovementIdentification{

  aircraftIdentification?: string ;//Aircraft Identification
  aircraftIdentificationPrevious?:string; //Aircraft Identification Previous
  globallyUniqueFlightIdentifier?: string;

}
export class RouteConstraint{

  departureOrArrivalCode?: string;
  description?: string;
  levelConstraintActivation?: string;
  levelConstraintCondition?: string;
  levelConstraintLevel?: string;
  restrictionReference?: string
  speedConstraintActivation?: string;
  speedConstraintCondition?: string;
  speedConstraintSpeed?: string;
  timeConstraintCondition?: string;
  timeSpecification?: string;

}

export class AircraftTransportFormation{
   Count?: number;
   Identifier?: string;
   AircraftTransportType?: AircraftTransportType[]

}

export class PackageGroupType{
  DangerousGoodsLimitation?: string;
  DangerousGoodsQuantity?: string;
  DangerousGoodsVolume?: string;
  DangerousGoodsUNNumber?: string;
  Division?: string;
  TransportRadiationLevelIndex?: string;
  DominantHazardClass?: string;
  GrossWeight?: string;
  NetWeight?: string;
  PackageQuantity?: string;
  PackingGroupCode?: string;
  ProperShippingName?: string;
}

export class CargoItem{
AirWaybillNumber: string
AircraftCargoLimitation?: string;
Category?: string
CompatibilityGroup?: string;
CriticalSafetyIndex?: string;
OnboardLocation?: string;
ShipmentAuthorisations?: string;
ShippingInformation?: string;
SubsidiaryHazardClassAndDivision?: string;
PackageGroupType: PackageGroupType[];
}

export class MeteorologicalEnvironment{
Temperature?: string;
WindDirection?: string;
WindSpeed?: string;
}

export class CargoItemType{

CommunicationCapabilityCode?: string;
ConstraintActivationCode?: string;
DatalinkCommunicationCapabilityCode?: string;
DepartureOrArrivalCode?: string;
DinghyCoverTypeCode?: string;
EmergencyPhaseCode?: string;
EmergencyRadioCapabilityTypeCode?: string;
EnRouteDelayTypeCode?: string;
LevelConditionCode?: string;
LifeJacketTypeCode?:string;
ModifiedRouteItemCode?: string;
NavigationAidServiceTypeCode?: string;
NavigationCapabilityCode?: string;
OtherRouteDesignatorCode?: string;
PackingGroupCode?: string;
PerformanceBasedNavigationCapabilityCode?: string;
RadioactiveMaterialCategoryCode?: string;
RouteTruncationCode?: string;
SpecialHandlingReasonCode?: string;
SpeedConditionCode?: string;
StandardCapabilitiesCode?: string;
SurveillanceCapabilityCode?: string;
SurvivalEquipmentTypeCode?: string
TimeConditionCode?: string;
TrajectoryPointPropertyTypeCode?: string;
WakeTurbulenceCategoryCode?: string;

}
