export const Model= JSON.stringify({"Identifier":["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:element","fx:point4D","fx:pointProperty","fx:reference","fx:identifier"],
"airfileRouteStartTime":["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:airfileRouteStartTime"], 
"alongRouteDistance":"alongRouteDistance_collection",
"altimeterSetting":"altimeterSetting_collection",  
"boundaryCrossingClearedLevel":["fx:Flight","fx:enRoute","fx:boundaryCrossingCoordination","fx:clearedLevel","flightLevel","_"], 
"boundaryCrossingLevel":["fx:Flight","fx:enRoute","fx:boundaryCrossingCoordination","fx:altitudeInTransition","fx:level"],
"boundaryCrossingTime":["fx:Flight","fx:enRoute","fx:boundaryCrossingCoordination","fx:crossingTime"],
"boundaryCrossingPoint":["fx:Flight","fx:enRoute","fx:boundaryCrossingCoordination","fx:crossingPoint"],
"cruisingLevel":["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:cruisingLevel"],
"cruisingSpeed": ["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:cruisingSpeed","_"],
"divertAirport":["fx:Flight","fx:arrival","fx:reclearanceInFlight","fx:filedRevisedDestinationAerodrome","iataDesignator"],
"elementStartPoint":"elementStartPoint_collection",
"estimatedElapsedTimeLongitude":["fx:Flight","fx:routeTrajectoryGroup","fx:current","fx:routeInformation","fx:estimatedElapsedTime","fx:location"],
"estimatedElapsedTimePoint": ["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:estimatedElapsedTime","fx:location","fx:point"],
"estimatedElapsedTimeRegion": "estimatedElapsedTimeRegion_collection",
"levelAltitude":"levelAltitude_collection",
"modifiedRouteItemReference":"modifiedRouteItemReference_collection",
"position":"position_collection",
"predictedAirspeed":"predictedAirspeed_collection",
"predictedGroundspeed":"predictedGroundSpeed_collection",
"routeDesignator":"routeDesignator_collection",
"routeToRevisedDestination":["fx:Flight","fx:arrival","fx:reclearanceInFlight","fx:routeToRevisedDestination"],
"RouteText":["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:routeText"],
"standardInstrumentArrivalIdentifier":"StandardInstrumentArrivalIdentifier_collection",
"totalEstimatedElapsedTime":["fx:Flight","fx:routeTrajectoryGroup","fx:agreed","fx:routeInformation","fx:totalEstimatedElapsedTime"],
"trajectoryPointDescription":"trajectoryPointDescription_collection",
"verticalRange":"VerticalRange_collection",
"rankedTrajectoryIdentifier":["fx:Flight","fx:routeTrajectoryGroup","fx:ranked","fx:identifier"]
})